# (실행 환경 공통 설정)
# : 개발 환경에 상관 없이 공통으로 적용되는 설정

server:
  error:
    include-stacktrace: NEVER # 자세한 에러 명세는 전달하지 않기

spring:
  profiles:
    group: # 프로필 그룹 생성 - 새로운 프로필명에, 하위 프로필들을 조합. 생성한 그룹은 spring.config.activate.on-profile 에서 명시해줘야함
      local8080: local, port8080
      dev8080: dev, port8080
      prod80: prod, port80
    default: local8080 # jar 실행시 프로필 설정이 없을 때 적용할 프로필
    # IDE 실행 프로필 설정은, 실행 - 구성편집에서 VM 옵션 안에 -Dspring.profiles.active=dev8080 이렇게 설정 가능
    # prod 실행 포트를 나눠둔 이유는 배포 서버의 무중단 배포시 스위칭을 위한 것
  mvc:
    pathmatch: # Swagger 에러 해결
      matching-strategy: ant_path_matcher

springdoc: # swaggerdoc 설정
  model-and-view-allowed: true # ModelAndView 허용
  use-fqn: true # Schema 정보를 package 명까지 붙여서 보여주기
  packages-to-scan: com.railly_linker.springboot_mvc_project_template.controllers # !!!프로젝트 패키지명에 따라 controllers 폴더 경로 지정!!
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8